chore(ci): colima resources change, pytest enabled

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -117,8 +117,7 @@ jobs:
         colima list
 
 
-        docker-compose -f deploy/docker-compose.yml -f deploy/docker-compose.otlp.yml --project-directory . up -d
-
+        # docker-compose -f deploy/docker-compose.yml -f deploy/docker-compose.otlp.yml --project-directory . up -d
 
     # - name: start lima for ${{ matrix.os }} on ${{ matrix.arch }}
     #   env:
@@ -131,89 +130,92 @@ jobs:
     #     lima nerdctl info
     #     make start-docker-ci-d
 
-    # - name: Brew deps for ${{ matrix.os }} on ${{ matrix.arch }}
-    #   env:
-    #     LANG: en_US.UTF-8
-    #     LC_CTYPE: en_US.UTF-8
-    #   run: |
-    #     brew install cmake || true  # macos image has cmake installed, but a new version may exist; ignore it if so
-    #     brew install doxygen || true
-    #     brew install hdf5 || true
-    #     brew install pkg-config || true
-    #     brew install wget || true
-    #     brew install jpeg || true
-    #     brew install libpng || true
-    #     brew install libtiff || true
-    #     brew install openexr || true
-    #     brew install eigen || true
-    #     brew install tbb || true
-    #     brew install hdf5 || true
-    #     # pytorch
-    #     brew install openblas || true
-    #     brew install libomp || true
-    #     brew install openmpi || true
-    #     brew install tcl-tk || true
-    #     brew install openssl || true
-    #     brew install readline || true
-    #     brew install sqlite3 || true
-    #     brew install xz || true
-    #     brew install zlib || true
-    #     # https://techblog.willshouse.com/2013/05/20/brew-install-gnu-stat/
-    #     brew install coreutils || true
-    #     brew install findutils || true
-    #     brew install gnu-tar || true
-    #     brew install gnu-sed || true
-    #     brew install gawk || true
-    #     brew install gnutls || true
-    #     brew install gnu-getopt || true
-    #     brew install libmagic || true
-    #     brew install libffi || true
-    #     brew install atomicparsley || true
-    #     brew install tree || true
-    #     brew install tesseract || true
+    - name: Brew deps for ${{ matrix.os }} on ${{ matrix.arch }}
+      env:
+        LANG: en_US.UTF-8
+        LC_CTYPE: en_US.UTF-8
+      run: |
+        brew install cmake || true  # macos image has cmake installed, but a new version may exist; ignore it if so
+        brew install doxygen || true
+        brew install hdf5 || true
+        brew install pkg-config || true
+        brew install wget || true
+        brew install jpeg || true
+        brew install libpng || true
+        brew install libtiff || true
+        brew install openexr || true
+        brew install eigen || true
+        brew install tbb || true
+        brew install hdf5 || true
+        # pytorch
+        brew install openblas || true
+        brew install libomp || true
+        brew install openmpi || true
+        brew install tcl-tk || true
+        brew install openssl || true
+        brew install readline || true
+        brew install sqlite3 || true
+        brew install xz || true
+        brew install zlib || true
+        # https://techblog.willshouse.com/2013/05/20/brew-install-gnu-stat/
+        brew install coreutils || true
+        brew install findutils || true
+        brew install gnu-tar || true
+        brew install gnu-sed || true
+        brew install gawk || true
+        brew install gnutls || true
+        brew install gnu-getopt || true
+        brew install libmagic || true
+        brew install libffi || true
+        brew install atomicparsley || true
+        brew install tree || true
+        brew install tesseract || true
 
+        # https://github.com/jiaaro/pydub#installation
+        # libav
+        brew install libav || true
+        ####    OR    #####
+        # SOURCE: https://matham.github.io/ffpyplayer/installation.html#using-binary-wheels
+        # ffmpeg
+        brew install ffmpeg || true
+        brew install sdl2 || true
+        brew install sdl2_mixer || true
 
-    #     # https://github.com/jiaaro/pydub#installation
-    #     # libav
-    #     brew install libav || true
-    #     ####    OR    #####
-    #     # SOURCE: https://matham.github.io/ffpyplayer/installation.html#using-binary-wheels
-    #     # ffmpeg
-    #     brew install ffmpeg || true
-    #     brew install sdl2 || true
-    #     brew install sdl2_mixer || true
+        make start-docker-services-d
 
-    #     make start-docker-services-d
+        docker ps
 
-    #     pg_isready -p 5432
+        # pg_isready -p 5432
 
-    # - name: link environment yaml for ${{ matrix.os }} on ${{ matrix.arch }}
-    #   run: |
-    #     make link-conda-ci
-    # - name: Set up Python for ${{ matrix.os }} on ${{ matrix.arch }}
-    #   uses: conda-incubator/setup-miniconda@v2.2.0
-    #   with:
-    #       # miniforge-variant: Mambaforge
-    #       # use-mamba: true
-    #     miniconda-version: "latest"
-    #     python-version: ${{ matrix.python }}
-    #       # channel-priority: strict
-    #     activate-environment: fastapi_pytorch_postgresql_sandbox3
-    #       # environment-file: ${{ env.CONDA_FILE }}
-    #       # NOTE: 'Set this option to "false" to disable running the post cleanup step of the action. Default is "true"'
-    #       # SOURCE: https://github.com/conda-incubator/setup-miniconda/blob/7e642bb2e4ca56ff706818a0febf72bb226d348d/action.yml
-    #     run-post: ${{ matrix.os != 'windows-latest' && 'true' || 'false' }}
+    - name: link environment yaml for ${{ matrix.os }} on ${{ matrix.arch }}
+      run: |
+        make link-conda-ci
 
-    # - name: Test with pytest for ${{ matrix.os }} on ${{ matrix.arch }}
-    #   run: |
-    #     inv ci.pytest -vvvvv
-    #   # pytest --junitxml=junit/test-results.xml --cov-report=xml -n auto tests --dist loadfile
-    # - name: Upload pytest test results
-    #   if: always()
-    #   uses: actions/upload-artifact@v1
-    #   with:
-    #     name: pytest-results
-    #     path: junit/test-results.xml
-    # - name: Upload coverage to Codecov
-    #   if: github.repository == 'bossjones/fastapi_pytorch_postgresql_sandbox'
-    #   uses: codecov/codecov-action@v3
+    - name: Set up Python for ${{ matrix.os }} on ${{ matrix.arch }}
+      uses: conda-incubator/setup-miniconda@v2.2.0
+      with:
+          # miniforge-variant: Mambaforge
+          # use-mamba: true
+        miniconda-version: "latest"
+        python-version: ${{ matrix.python }}
+          # channel-priority: strict
+        activate-environment: fastapi_pytorch_postgresql_sandbox3
+          # environment-file: ${{ env.CONDA_FILE }}
+          # NOTE: 'Set this option to "false" to disable running the post cleanup step of the action. Default is "true"'
+          # SOURCE: https://github.com/conda-incubator/setup-miniconda/blob/7e642bb2e4ca56ff706818a0febf72bb226d348d/action.yml
+        run-post: ${{ matrix.os != 'windows-latest' && 'true' || 'false' }}
+
+    - name: Test with pytest for ${{ matrix.os }} on ${{ matrix.arch }}
+      run: |
+        inv ci.pytest -vvvvv
+
+    - name: Upload pytest test results
+      if: always()
+      uses: actions/upload-artifact@v1
+      with:
+        name: pytest-results
+        path: junit/test-results.xml
+
+    - name: Upload coverage to Codecov
+      if: github.repository == 'bossjones/fastapi_pytorch_postgresql_sandbox'
+      uses: codecov/codecov-action@v3
